### ISSUE TITLE
subRVIS site is down

### ISSUE THREAD

**Issue by lclcgcmn** [igm-team/subrvis#4]
http://www.subrvis.org/ has been down since yesterday. The error message we receive is "502 Bad Gateway
nginx/1.10.2" when we try to access the site. This happens in all the browsers we tried. Will this site be available soon?

**Comment by gussow** [comment]
Thanks for letting us know! I will look into it, hopefully we can have it up shortly. Apologies!

**Comment by lclcgcmn** [comment]
Thank you! We really like this tool. :)

**Comment by gussow** [comment]
Happy to hear! :)

It seems to be a server issue across a few of our websites, I've been in touch with IT to see what is wrong.

**Comment by gussow** [comment]
The site should be back up! Let me know if it works for you - thanks!

**Comment by lclcgcmn** [comment]
It is working, which is great. Thank you very much for looking into this, it is greatly appreciated. Please have a good weekend!

**Comment by gussow** [comment]
Thanks! You too!
