### ISSUE TITLE
subRVIS site is down 

### ISSUE THREAD

**Issue by NM-G08** [igm-team/subrvis#5]
Hello,

I work with lclcgcmn and wanted to let you know that the subrvis.org site is down again.  I keep getting the following error on the webpage.

![image](https://user-images.githubusercontent.com/43679337/46217368-d3321280-c30f-11e8-9c55-a81754d4a48b.png)

Could you look into this or let us know if we are doing something wrong?

Thanks!
Nikita

**Comment by gussow** [comment]
Hello Nikita,

Are you still getting an error? Thanks!

Ayal

**Comment by NM-G08** [comment]
Hello Ayal,

No, I'm no longer getting that error page; it opens to the home page almost like it used to.  However, the entire page has a gray overlay.  I can type in the plot variants section, but the plot function also doesn't work.

Thanks,
Nikita

**Comment by gussow** [comment]
Hi Nikita,

Got it, thanks for letting me know. At this time the site is working for me, so I'm not certain why you're getting the gray overlay.

Can you give me a few more details, and I'll try to recreate the error and debug it? Specifically, what browser are you using and on what OS? Does this gray overlay happen for all genes that you try to plot?

Ayal

**Comment by NM-G08** [comment]
Hi,

I'm on Windows 7 Professional for the OS.  I'm realizing now that it is only in Chrome where there is an issue (it works in Internet Explorer at least).  I don't know if this makes a difference, but I think URL says Not secure now, which it may or may not have said before. 

Chrome screenshot:
![image](https://user-images.githubusercontent.com/43679337/46441088-6d8cbe80-c733-11e8-97ab-3aa0ec5572d0.png)

Thanks for looking into this,
Nikita

**Comment by gussow** [comment]
Hi Nikita,

No problem, happy to try to debug this. 

Unfortunately I can't seem to recreate this error. Chrome saying "Not Secure" is due to a change in how they flag sites that are HTTP vs HTTPS, so in theory should not affect whether the site works. I assume other sites labelled "Not Secure" do work? Are you using the latest version of Chrome?

Ayal

**Comment by NM-G08** [comment]
Hi,

I am using the latest version of Chrome.  I do also see other sites labeled with "Not Secure", so you're right it probably doesn't matter.  I will say I just tried the website on my personal computer and it works fine.  I do wonder if there is something from the Mayo Clinic that is causing the site not to work.  If it's not too much trouble for you to look into, I'm happy to send you any information you may need.  Otherwise, I can switch over to using IE for the subrvis.org page.

Thanks!
Nikita

**Comment by gussow** [comment]
Hi Nikita,

Hmm, interesting - got it. For now I'll mark this issue resolved, and if any more similar complaints come through we can see if there is a common thread and try to resolve it.

Thanks and let me know if there is anything else you need!

Ayal
